# Generated by Django 5.0.6 on 2024-07-07 22:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_product_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='sku',
        ),
        migrations.RemoveField(
            model_name='productvariation',
            name='product',
        ),
        migrations.AlterField(
            model_name='productvariation',
            name='sku',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variations', to='core.product'),
        ),
    ]
